typography_spectrum: 0.04212079499848187
color:
  brandStrength: 0.3545487984083593
  lightness: 0.3310725735500455
  saturation: 0.2886769021861255
  rhythmicContrast: 0.7349482055287808
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/29a96418-32e9-42a7-b640-835460cfb247.jpg
  appId: jimmyturturici
layout_spectrum: 0.12530109798535705
author:
  name: Jimmy Turturici
  email: jimmyturturici@gmail.com
  url: www.naturalsatellite.net
name: Natural Satellite
title: Jimmy Turturici
