typography_spectrum: 0.04212079499848187
color:
  brandStrength: 0.3545487984083593
  lightness: 0.3310725735500455
  saturation: 0.2886769021861255
  rhythmicContrast: 0.7349482055287808
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
opengraph:
  image: null
  appId: ''
layout_spectrum: 0.12530109798535705
author:
  name: Jimmy Turturici
  email: jimmyturturici@gmail.com
  url: www.naturalsatellite.net
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/350101a9-556a-44cb-a65b-c79f2a3a2512.jpg
name: Natural Satellite
navigation:
  - name: Aurora...
    url: >-
      http://www.imposemagazine.com/bytes/chatter/week-in-pop-prince-samo-manatree-sir-rose-selavy-templo-x-the-last-hurrah-thurst-not-the-1s-ruane-maurice-we-are-temporary-ryan-sambol#jimmy-turturici
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f751dd47-737b-4fc1-9a6b-191627c70a69.jpg
title: Jimmy Turturici
